CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(150) UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    trial_started_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    trial_ends_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT chk_tenants_status
        CHECK (status IN ('TRIAL', 'ACTIVE', 'EXPIRED'))
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    description VARCHAR(120) NOT NULL,
    image_url VARCHAR(200),
    active BOOLEAN NOT NULL,
    tenant_id BIGINT NOT NULL,
    CONSTRAINT uq_categories_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    image_url VARCHAR(200),
    stock INTEGER NOT NULL,
    active BOOLEAN,
    category_id BIGINT,
    tenant_id BIGINT
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    tenant_id BIGINT NOT NULL
);

CREATE TABLE tenant_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    whatsapp VARCHAR(255),
    logo_url VARCHAR(255),
    cover_url VARCHAR(255),
    primary_color VARCHAR(255),
    background_color VARCHAR(255),
    welcome_message VARCHAR(255),
    address VARCHAR(255),
    open BOOLEAN NOT NULL,
    tenant_id BIGINT NOT NULL UNIQUE
);

ALTER TABLE categories
    ADD CONSTRAINT fk_categories_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id);

ALTER TABLE products
    ADD CONSTRAINT fk_products_category
    FOREIGN KEY (category_id) REFERENCES categories(id),
    ADD CONSTRAINT fk_products_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id);

ALTER TABLE tenant_config
    ADD CONSTRAINT fk_tenant_config_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id);
