spring.application.name=backend

# Base de datos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tomapedido}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# JWT
app.jwt.secret=${JWT_SECRET}

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway queda deshabilitado hasta realizar el baseline controlado de la base existente.
spring.flyway.enabled=true
