spring.application.name=backend

# Base de datos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tomapedido}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

# JWT
app.jwt.secret=${JWT_SECRET:TomaPedido-Secret-Key-Para-JWT-2026-Muy-Segura}

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
